### ISSUE TITLE
Test results - using attribute to represent "constant with parameters - top(elevations)"

### ISSUE THREAD

**Issue by zhangyuanlin** [Topology/ALM-Compiler#10]
Given
```
             elevations :: things
              attributes
                top: points
 ```
The instance 
``` 
  instances
        box in elevations
            top = top(box) 
```
is translated into 

```
elevations_top(box, T_) :- instance(top(box), points), elevations_top(box, TO), T_=TO.
```

top(box) in the instance is understood by CALM as applying function top to box. 
Can it be understood as a Herbrand term?  in fact, we do have the following instance in the same program.

```
        top(X) in movable_points where instance(X, elevations)
```
In summary, what is the right understanding of a right-hand side *term* in instantiation? 
(If it is understood as an Herbrand term, then attributes seem (is conjectured) to be used to represent "constants with parameters as in ALM paper")

**Comment by zhangyuanlin** [comment]
Thanks. I think here we need to decide if we want to allow people to use function to define an instance.
For example, in
``` 
  instances
        box in elevations
            top = top(box) 
```
do we allow top(..) to be a function? 

For now, one **proposal** is 
```
1. all terms in right-hand side in an instantiation are understood as Herbrand terms. 
1.1 current CALM allows to define an instance using Herbrand term, e.g., top(box) in points 
2. in future, we can discuss if we allow function to be used in instantiation. 
2.1. This issue may be also related if we want to introduce "record sort" (e.g., we can declare 
                           top(elevations) :: points -- [you use a different syntax in the relevant discussion] 
       )

**Comment by Topology** [comment]
From Discussion
```

        box in elevations
            top = top(box)
			
		top(X) in movable_points where instance(X, elevations)
		

				
		-------------- BROKEN---------
		% Sort Instance [box] for sort [elevations].
		is_a(box, elevations) :- instance(elevations_top(box), points).



		% Sort Instance [elevations_top(X)] for sort [movable_points].
		is_a(elevations_top(X), movable_points) :- instance(X, elevations).




		% Definition of attribute [top] for instance [box] of sort [elevations].
		elevations_top(box, T_) :- instance(elevations_top(box), points), elevations_top(box, TO), T_=TO.




		------------------  Attempted fix, but circular ----------------------

		% Sort Instance [box] for sort [elevations].
		is_a(box, elevations) :- instance(top(box), points).


		% Sort Instance [elevations_top(X)] for sort [movable_points].
		is_a(top(X), movable_points) :- instance(X, elevations).

		% Definition of attribute [top] for instance [box] of sort [elevations].
		elevations_top(box, T_) :- instance(top(box), points), T_=top(box).




		-----------------------


		% Sort Instance [box] for sort [elevations].
		is_a(box, elevations) :- (where clauses).

		% Definition of attribute [top] for instance [box] of sort [elevations].
		elevations_top(box, T_) :- instance(top(box), points), T_=top(box), (where clauses).


		% Sort Instance [elevations_top(X)] for sort [movable_points].
		is_a(top(X), movable_points) :- instance(X, elevations).


		1. remove instance requirements on range of attribute functions for definition.  (when herbrand)
		2. RHS as herbrand, not function

**Comment by Topology** [comment]
Will likely need to add marker to herbrand terms in attribute function definition.  

Skip type checking for now, do what needs to be done to get the string literal forward.

**Comment by Topology** [comment]
Latest calm.jar can now run these two programs that have herbrand terms assigned to attributes.  

program 1: 

	system description monkeyBanana
		theory basic_motion
		  module moving
			sort declarations
				points, things :: universe
				movable_points :: points

				% intended: the instances of movable_points
				%           are surface(X) where X is an elevation
				%           the instances of elevations are some objects
				%           whose attribute is an elment in points. 
				elevations :: things
				  attributes
					top: points


		structure monkey_and_banana
		instances
			box in elevations
				top = surface(box)

			surface(X) in movable_points where instance(X, elevations)

program 2: 

    system description test
        theory test
          module test
            sort declarations

                things :: universe
                locations :: universe
                elevations :: universe
                   attributes
                      top: locations

                things_with_elevations :: things

        structure attribute_test
            instances

                top2(X) in locations where instance(X, elevations)

                X in elevations where instance(X, things_with_elevations)
                    top = top2(X)

                box in things_with_elevations

I do not consider these permanent solutions.  We need to formally model herbrand terms in the compiler.  I disabled several aspects of type checking and translation error checking to put these through quickly.  

Program 2 did not have circularity in instance definitions.   I had to disable the `instance(surface(box), points)` condition in program 1 to make it non-circular.

**Comment by Topology** [comment]
I just uploaded a distribution that I believe resolves this issue for now.  Please verify.   The program posted in this issues, however, has other issues.   The compiler is now reporting name collisions.  (See Below)   I believe these name collision errors are correct for the posted program.     I am closing this issue.   If there are any further issues related to this, I believe the code base has migrated enough to warrant a new issue being created.  

        --------------------------
        ---- NO SYNTAX ERRORS ----
        --------------------------

        -------------------------
        ---- SEMANTIC ERRORS ----
        -------------------------

        ErrorID: NAM003
        Message: Sort Instance [box at (test.alm:118:8)] cannot have the same name as element [box:elevations at (test.alm:79:3)].
        Explanation: The names of sort instances must be new and not collide with functions, constants or previously defined sort instances.
        Recommendation: Change the name of one of the elements to avoid name collision.

        ErrorID: NAM003
        Message: Sort Instance [top(X) at (test.alm:122:8)] cannot have the same name as element [top:points at (test.alm:12:16)].
        Explanation: The names of sort instances must be new and not collide with functions, constants or previously defined sort instances.
        Recommendation: Change the name of one of the elements to avoid name collision.
